// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 23.8.2025, 14:25:49
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/StretzS/inequality/apps/fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/StretzS/inequality/apps/fe/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/StretzS/inequality/apps/fe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/StretzS/inequality/apps/fe/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/StretzS/inequality/apps/fe/plugins/**/*.{js,ts,mjs}","C:/Users/StretzS/inequality/apps/fe/composables/**/*.{js,ts,mjs}","C:/Users/StretzS/inequality/apps/fe/utils/**/*.{js,ts,mjs}","C:/Users/StretzS/inequality/apps/fe/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/StretzS/inequality/apps/fe/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/StretzS/inequality/apps/fe/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/StretzS/inequality/apps/fe/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;